### ISSUE TITLE
Help on "ERROR:root:No internal standard was provided."

### ISSUE THREAD

**Issue by tan294-niu** [thatchemistryguy/PyParse#7]
Hello,
 
I was trying to implement the examples you provided by 'python PyParse.py example_rpt.rpt example_platemap.csv -o test_dir -r 8 -c 12 -pt corrP/STD', but I got 'INFO:root:PyParse was run from the following directory: /Users/tan294/Documents/UM_Postdoc/MassSpecAnalysis/PyParse-main/test.
INFO:root:The output files were saved to new_output_directory/.
INFO:root:A Boc group was found and disconnected for Product13.
INFO:root:A Boc group was found and disconnected for Product14.
INFO:root:A Boc group was found and disconnected for Product15.
INFO:root:A Boc group was found and disconnected for Product17.
INFO:root:A Boc group was found and disconnected for Product18.
ERROR:root:No internal standard was provided. Halting program.
' in the logfile.txt. Could you suggest what the issue could be? Thank you very much for your help!

**Comment by thatchemistryguy** [comment]
Hi!

It's because you've selected corrP/STD (corrected ratio of product to internal standard) as the plot_typr, but not specified an internal standard in the platemap. If there is an internal standard in your plate, you can specify this in the platemap (and make sure your column header in the platemap matches exactly what's in the documentation); if not, try using Parea as the plot type instead (i.e. -pt Parea). 

Hope this helps!
